/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class CustomJNI */

#ifndef _Included_CustomJNI
#define _Included_CustomJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CustomJNI
 * Method:    splitFile
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_CustomJNI_splitFile
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
